name: Build OmniX OS ISO

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Stazeni zdroju
      uses: actions/checkout@v4

    - name: Instalace zavislosti
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc clang lld llvm grub-pc-bin grub-efi-amd64-bin xorriso mtools

    - name: Kompilace jadra s grafikou
      run: |
        cd linux-7.0.3
        make ARCH=x86_64 LLVM=1 defconfig
        make ARCH=x86_64 LLVM=1 kvm_guest.config
        
        # Zapnuti zakladniho grafickeho zobrazovace pro Limbo
        # Úplné vnucení základní konzole
        ./scripts/config -e CONFIG_VGA_CONSOLE
        ./scripts/config -e CONFIG_DUMMY_CONSOLE
        ./scripts/config -d CONFIG_DRM_BOCHS
        make ARCH=x86_64 LLVM=1 olddefconfig
        
        make ARCH=x86_64 LLVM=1 -j$(nproc)

    - name: Tvorba bootovaciho ISO
      run: |
        mkdir -p isodir/boot/grub
        cp linux-7.0.3/arch/x86/boot/bzImage isodir/boot/
        
        # Vytvoreni GRUB menu (Upravene pro spravne zobrazeni!)
        cat << 'GRUB' > isodir/boot/grub/grub.cfg
        set timeout=3
        menuentry "OmniX OS (Core)" {
            set gfxpayload=keep
            linux /boot/bzImage console=tty0 console=ttyS0 vga=normal nomodeset
        }
        GRUB
        
        grub-mkrescue -o OmniX-OS.iso isodir

    - name: Ulozeni ISO na GitHub
      uses: actions/upload-artifact@v4
      with:
        name: omnix-os-iso
        path: OmniX-OS.iso
