name: Build OmniX OS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalace nástrojů pro ISO
        run: sudo apt-get update && sudo apt-get install -y nasm xorriso

      - name: Kompilace OmniX OS
        run: |
          rustup target add i686-unknown-linux-gnu
          nasm -f bin omnix-files/bootloader/asm/boot.asm -o boot.bin

          rustc --target i686-unknown-linux-gnu -C panic=abort -C opt-level=2 -C relocation-model=static -C no-redzone=y -C code-model=kernel -C target-feature=-mmx,-sse,+soft-float --emit obj omnix-files/kernel/rust/main.rs -o kernel.o

          ld -m elf_i386 -T omnix-files/linker.ld kernel.o -o kernel.bin

          cat boot.bin kernel.bin > temp.bin
          dd if=/dev/zero of=padding.bin bs=1 count=32768
          cat temp.bin padding.bin | head -c 32768 > omnix_core.bin

          mkdir -p isodir
          cp omnix_core.bin isodir/
          xorriso -as mkisofs -R -J -b omnix_core.bin -no-emul-boot -boot-load-size 64 -o omnix_os.iso isodir

      - name: Upload OmniX OS ISO
        uses: actions/upload-artifact@v4
        with:
          name: omnix-os-iso
          path: omnix_os.iso

      - name: Nastavení Pythonu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalace knihoven pro bota
        run: pip install -r bot/requirements.txt

      - name: Odeslání zprávy na Discord
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          PING_ID: "<@&1502000912342843523>"
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: python bot/discord_notifier.py
